# -*- coding: utf-8 -*-
"""Generate Appendix B (full per-question-type tables) from results/*.json."""

from __future__ import annotations

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(os.path.dirname(os.path.dirname(HERE)), "results")
OUT = os.path.join(HERE, "appendix_b_tables.md")

METRICS = ["R@1", "R@5", "R@10", "MRR", "nDCG@10", "tIoU@1"]
TYPE_ORDER = ["CW", "TN", "CH", "TC", "TP"]
TYPE_LABEL = {"CW": "CW (causal why)", "CH": "CH (causal how)",
              "TN": "TN (temporal next)", "TC": "TC (temporal current)",
              "TP": "TP (temporal previous)"}


def fmt(v: float) -> str:
    return f"{v:.3f}".lstrip("0") if isinstance(v, float) else str(v)


def retrieval_table(fname: str, modality: str = "visual") -> str:
    with open(os.path.join(RESULTS, fname), encoding="utf-8") as f:
        d = json.load(f)
    r = d["results"][modality]
    lines = ["| Type | n | " + " | ".join(METRICS) + " |",
             "|---|---|" + "---|" * len(METRICS)]
    lines.append("| overall | " + str(d["n_evaluated"]) + " | "
                 + " | ".join(fmt(r["overall"][m]) for m in METRICS) + " |")
    for t in TYPE_ORDER:
        row = r["by_type"].get(t)
        if row:
            lines.append(f"| {TYPE_LABEL[t]} | {row['n']} | "
                         + " | ".join(fmt(row[m]) for m in METRICS) + " |")
    return "\n".join(lines)


def qa_table(fname: str) -> str:
    with open(os.path.join(RESULTS, fname), encoding="utf-8") as f:
        d = json.load(f)
    by: dict[str, list] = {}
    for x in d["results"]:
        by.setdefault(x["qtype"], []).append(x["correct"])
    lines = ["| Type | n | Accuracy |", "|---|---|---|",
             f"| overall | {d['n']} | {fmt(d['accuracy'])} |"]
    for t in TYPE_ORDER:
        xs = by.get(t)
        if xs:
            lines.append(f"| {TYPE_LABEL[t]} | {len(xs)} | {fmt(sum(xs) / len(xs))} |")
    return "\n".join(lines)


SECTIONS = [
    ("B.1 ViT-B-32 baseline — corpus scope (visual, tau 0.5)", "eval_val_corpus.json"),
    ("B.2 ViT-B-32 baseline — video scope (visual, tau 0.5)", "eval_val_video.json"),
    ("B.3 Decomposition + visual re-ranking — corpus scope", "eval_val_corpus_decomp_rerank.json"),
    ("B.4 Decomposition + visual re-ranking — video scope", "eval_val_video_decomp_rerank.json"),
    ("B.5 SigLIP + decomposition (final best) — corpus scope", "eval_val_corpus_siglip_decomp.json"),
    ("B.6 SigLIP + decomposition (final best) — video scope", "eval_val_video_siglip_decomp.json"),
]

QA_SECTIONS = [
    ("B.7 QA accuracy by type — simple agent, text-only (150 questions)", "qa_simple_150.json"),
    ("B.8 QA accuracy by type — graph agent, text-only (150 questions)", "qa_graph_150.json"),
    ("B.9 QA accuracy — multimodal simple agent (44 TN questions)", "qa_claude_tn44.json"),
]

parts = ["# Appendix B — Full per-question-type result tables",
         "",
         "Generated by `make_appendix_b.py` from the committed result files in "
         "`results/`; regenerate after any re-run. Question types: CW/CH causal, "
         "TN/TC/TP temporal. TP has only 52 grounded instances corpus-wide "
         "(2 in the 150-question QA sample) — its rows are reported for "
         "completeness and should not be interpreted.", ""]
for title, fname in SECTIONS:
    parts += [f"## {title}", "", retrieval_table(fname), ""]
for title, fname in QA_SECTIONS:
    parts += [f"## {title}", "", qa_table(fname), ""]

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(parts))
print("wrote", OUT)
